# panel3_coordinates.py

import streamlit as st
import pandas as pd
from io import BytesIO
import uuid


def render_panel3(coord_df):
    """
    Panel 3 - Pseudo-3D Joint Coordinates

    Parameters
    ----------
    coord_df : pandas.DataFrame

    Expected columns:
        Joint
        u
        v
        z (optional, only in 3D mode)
    """

    # ===================================
    # Panel Header
    # ===================================

    st.markdown("""
    <style>
    .panel-box{
        background-color:#1E293B;
        padding:15px;
        border-radius:12px;
        border:1px solid #334155;
        margin-bottom:10px;
    }

    .panel-title{
        color:white;
        font-size:22px;
        font-weight:bold;
    }
    </style>
    """, unsafe_allow_html=True)

    st.markdown("""
    <div class="panel-box">
        <div class="panel-title">
            📍 3. PSEUDO-3D JOINT COORDINATES (u,v,z)
        </div>
    </div>
    """, unsafe_allow_html=True)

    # ===================================
    # Joint Count
    # ===================================

    st.metric(
        "Total Joints",
        len(coord_df)
    )

    # ===================================
    # Coordinate Table
    # ===================================

    st.dataframe(
        coord_df,
        use_container_width=True,
        height=420
    )

    st.caption(
        "Pseudo-3D joint coordinates generated by combining "
        "YOLO11m-Pose image coordinates (u,v) with MiDaS depth values (z)."
    )

    # ===================================
    # Export Buttons — unique key per render
    # ===================================

    # Generate a unique suffix so buttons don't clash
    # when multiple people are detected in one run
    unique_key = str(uuid.uuid4())[:8]

    col1, col2 = st.columns(2)

    csv_data = coord_df.to_csv(index=False)

    with col1:
        st.download_button(
            label="📄 Export CSV",
            data=csv_data,
            file_name="joint_coordinates.csv",
            mime="text/csv",
            use_container_width=True,
            key=f"csv_download_{unique_key}"
        )

    excel_buffer = BytesIO()

    with pd.ExcelWriter(
        excel_buffer,
        engine="openpyxl"
    ) as writer:

        coord_df.to_excel(
            writer,
            index=False,
            sheet_name="Coordinates"
        )

    excel_buffer.seek(0)

    with col2:
        st.download_button(
            label="📊 Export Excel",
            data=excel_buffer,
            file_name="joint_coordinates.xlsx",
            mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            use_container_width=True,
            key=f"excel_download_{unique_key}"
        )
