# panel2_depth.py

import streamlit as st
import numpy as np


def render_panel2(
    depth_image,
    z_values=None
):
    """
    Panel 2 - Depth Map Visualization

    Parameters
    ----------
    depth_image : np.ndarray
        MiDaS depth map visualization image

    z_values : list
        List of extracted Z values
    """

    # =====================================
    # Panel Header
    # =====================================

    st.markdown("""
    <style>
    .panel-box{
        background-color:#1E293B;
        padding:15px;
        border-radius:12px;
        border:1px solid #334155;
        margin-bottom:10px;
    }

    .panel-title{
        color:white;
        font-size:22px;
        font-weight:bold;
    }
    </style>
    """, unsafe_allow_html=True)

    st.markdown("""
    <div class="panel-box">
        <div class="panel-title">
            🌈 2. DEPTH MAP VISUALIZATION
        </div>
    </div>
    """, unsafe_allow_html=True)

    # =====================================
    # Depth Map
    # =====================================

    st.image(
        depth_image,
        channels="BGR",
        use_container_width=True
    )

    st.caption(
        "Near (High Z)  →  Far (Low Z)"
    )

    # =====================================
    # Depth Statistics
    # =====================================

    if z_values is not None and len(z_values) > 0:

        z_values = np.array(z_values)

        col1, col2, col3 = st.columns(3)

        with col1:
            st.metric(
                "Average Z",
                f"{z_values.mean():.1f}"
            )

        with col2:
            st.metric(
                "Min Z",
                f"{z_values.min():.1f}"
            )

        with col3:
            st.metric(
                "Max Z",
                f"{z_values.max():.1f}"
            )

    # =====================================
    # Color Legend
    # =====================================

    st.markdown("### Depth Interpretation")

    st.markdown("""
    🟡 **Yellow** → Near

    🟠 **Orange** → Near-Mid

    🟣 **Purple** → Mid Distance

    ⚫ **Black** → Far
    """)

    # =====================================
    # Description
    # =====================================

    st.info(
        "This panel displays the depth map generated by the MiDaS model. "
        "The depth value (Z) at each detected body joint is extracted and "
        "combined with the YOLO11m-Pose image coordinates (u,v) to generate "
        "pseudo-3D joint coordinates (u,v,z)."
    )